ALTER TYPE "RunnerStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "RunnerStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "RunnerStatus" ADD VALUE IF NOT EXISTS 'SUSPENDED';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT';

ALTER TABLE "RunnerProfile" ADD COLUMN IF NOT EXISTS "phone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "RunnerProfile" ADD COLUMN IF NOT EXISTS "bio" TEXT NOT NULL DEFAULT '';
ALTER TABLE "RunnerProfile" ADD COLUMN IF NOT EXISTS "transportMethod" TEXT NOT NULL DEFAULT '';
ALTER TABLE "RunnerProfile" ADD COLUMN IF NOT EXISTS "availabilityNotes" TEXT NOT NULL DEFAULT '';
ALTER TABLE "RunnerProfile" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
ALTER TABLE "RunnerProfile" ADD COLUMN IF NOT EXISTS "rejectedAt" TIMESTAMP(3);
ALTER TABLE "RunnerProfile" ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT;
ALTER TABLE "RunnerProfile" ADD COLUMN IF NOT EXISTS "suspendedAt" TIMESTAMP(3);
